defaults:
  - data_manipulations@diffusion_coordinates: diffusion_encodings
  - liftings@_here_: ${get_required_lifting:${dataset},${model}}

diffusion_coordinates:
  max_pe_dim: 3
  diffusion_time: 1.0
  include_first: false
  concat_to_x: false
  method: exact
